# Generated by Django 4.2.6 on 2024-01-24 18:10

import apps.Menu.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название напитка')),
                ('img', models.ImageField(blank=True, null=True, upload_to=apps.Menu.models.menu_image_path, verbose_name='Изображение 1')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание напитка')),
                ('price', models.CharField(max_length=400, verbose_name='Цена')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='Menu.category')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('img', models.ImageField(blank=True, null=True, upload_to=apps.Menu.models.menu_image_path, verbose_name='Изображение ')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание блюда')),
                ('ingredients', models.CharField(blank=True, max_length=204, null=True, verbose_name='Ингредиенты')),
                ('price', models.CharField(max_length=400, verbose_name='Цена')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='Menu.category')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
