# Generated by Django 4.2.6 on 2024-01-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_drinkcategory_alter_category_options_alter_drink_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория блюда', 'verbose_name_plural': 'Категории блюд'},
        ),
    ]
