# Generated by Django 4.2.6 on 2024-01-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)'),
        ),
    ]
