# Generated by Django 4.2.6 on 2024-02-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Цена'),
        ),
    ]
