# Generated by Django 4.2.6 on 2024-02-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QR_code', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_code_image',
        ),
    ]
