# Generated by Django 4.2.6 on 2024-01-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
