# Generated by Django 4.2.6 on 2024-02-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_code', '0002_alter_qrcode_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='url',
            field=models.CharField(max_length=180, unique=True, verbose_name='URL'),
        ),
    ]
