# Generated by Django 4.2.6 on 2024-01-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_code', '0002_alter_qrcode_created_at_alter_qrcode_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'verbose_name': 'QR Code', 'verbose_name_plural': 'QR Codes'},
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_code_image/', verbose_name='QR Code Image'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='url',
            field=models.URLField(unique=True, verbose_name='URL'),
        ),
    ]
