# Generated by Django 4.2.6 on 2024-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_code', '0002_remove_qrcode_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='Generated QR code image', null=True, upload_to='qr_code_image/', verbose_name='QR Code Image'),
        ),
    ]
