# Generated by Django 4.2.6 on 2024-01-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.TextField(max_length=304, verbose_name='Содержание'),
        ),
    ]
