# Generated by Django 4.2.6 on 2024-02-20 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Drink', '0001_initial'),
        ('Dish', '0002_alter_dish_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('dishes', models.ManyToManyField(blank=True, related_name='orders', to='Dish.dish', verbose_name='Блюда')),
                ('drinks', models.ManyToManyField(blank=True, related_name='orders', to='Drink.drink', verbose_name='Напитки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
