# Generated by Django 4.2.6 on 2024-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '😞 Удовлетворительно'), (2, '😐 Посредственно'), (3, '😊 Хорошо'), (4, '😄 Отлично'), (5, '🌟 Великолепно')], default=5, verbose_name='Рейтинг'),
        ),
    ]
