# Generated by Django 4.2.6 on 2024-02-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[('😞 Удовлетворительно', '😞 Удовлетворительно'), ('😐 Посредственно', '😐 Посредственно'), ('😊 Хорошо', '😊 Хорошо'), ('😄 Отлично', '😄 Отлично'), ('🌟 Великолепно', '🌟 Великолепно')], default=5, verbose_name='Рейтинг'),
        ),
    ]
